name: Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: crate-ci/typos@455c7cef71e047280f813fa4f1fe15b91c9a6d24 # v1
        with:
          config: .typos.toml
